language: python

os:
  - linux

python:
  - "3.7"

node_js:
  - 12

install:
  - pip install -r requirements.txt
  - npm install

script:
  - pytest

after_success:
  - test $TRAVIS_BRANCH = "master" && sls deploy