"""empty message

Revision ID: 00e19d8b3f17
Revises: 
Create Date: 2020-07-04 10:22:09.332020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e19d8b3f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('search_date_date', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lon', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_offers')
    # ### end Alembic commands ###
